"""
Emit the one root command a node is allowed to run, and the rule that allows it.

`update` is the only capability that needs root without a human present, and it
needs exactly two commands: refresh the package lists, then upgrade. Giving the
node account a general sudo rule to achieve that would mean any bug in the node
process is root — the same bug that today only reaches an unprivileged account.

So the grant is a **wrapper script**, and the sudoers rule names that one path
with no arguments. Two properties make it worth doing:

* the wrapper lives somewhere **root owns and the node cannot write** — putting
  it inside the install prefix would be pointless, since that belongs to the
  node's own account, which could then rewrite what it is allowed to run;
* it takes no arguments and runs a fixed argv, so there is nothing for the node
  to influence: not a package name, not a flag, not a shell string.

    python scripts/nmesh_sudoers.py --wrapper     # the script's contents
    python scripts/nmesh_sudoers.py --rule nmesh  # the sudoers line

Everything except the requested artefact goes to stderr: install.sh captures
stdout.
"""
import importlib.util
import os
import shutil
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Loaded from its file rather than as ``src.apps.fleet_host``: importing the
# package pulls in the mesh node and, with it, liboqs, which prints a banner on
# stdout — and stdout here carries the artefact install.sh writes to disk.
_spec = importlib.util.spec_from_file_location(
    "nmesh_fleet_host", os.path.join(ROOT, "src", "apps", "fleet_host.py"))
fleet_host = importlib.util.module_from_spec(_spec)
# Registered before it runs: `@dataclass` looks the defining module up in
# sys.modules, and a module loaded outside the import system is not there yet.
sys.modules[_spec.name] = fleet_host
_spec.loader.exec_module(fleet_host)

WRAPPER_PATH = "/usr/local/lib/nmesh/nmesh-update"


def _plan():
    """The detected package manager's refresh and upgrade argv, absolute."""
    for name, binary, plan in fleet_host._PACKAGE_MANAGERS:
        path = shutil.which(binary)
        if not path:
            continue
        steps = []
        for key in ("refresh", "upgrade"):
            argv = plan.get(key)
            if argv:
                steps.append([path] + list(argv[1:]))
        if steps:
            return name, steps
    return None, []


def _quote(argument: str) -> str:
    return "'" + argument.replace("'", "'\\''") + "'"


def wrapper() -> str:
    name, steps = _plan()
    if not steps:
        raise SystemExit("no package manager this node knows how to drive")
    lines = [
        "#!/bin/sh",
        "# NMesh — the one command the node account may run as root.",
        "#",
        "# Generated by install.sh --allow-update. It takes no arguments and runs",
        f"# a fixed sequence for {name}: nothing the node sends can influence it.",
        "# Owned by root and not writable by the node, or allowing it would mean",
        "# nothing.",
        "set -e",
        'if [ "$#" -ne 0 ]; then echo "this command takes no arguments" >&2; exit 2; fi',
        "export DEBIAN_FRONTEND=noninteractive",
    ]
    for index, argv in enumerate(steps, start=1):
        lines.append(f'echo "::nmesh-step::{index}/{len(steps)} {os.path.basename(argv[0])}"')
        lines.append(" ".join(_quote(part) for part in argv))
    lines.append('echo "::nmesh-step::done"')
    return "\n".join(lines) + "\n"


def rule(account: str) -> str:
    if not account or any(character.isspace() for character in account):
        raise SystemExit("invalid account name")
    return (f"# NMesh: {account} may run this one script as root, and nothing "
            f"else.\n"
            f"{account} ALL=(root) NOPASSWD: {WRAPPER_PATH}\n")


def main(argv) -> int:
    if "--wrapper" in argv:
        sys.stdout.write(wrapper())
        return 0
    if "--rule" in argv:
        index = argv.index("--rule")
        account = argv[index + 1] if index + 1 < len(argv) else "nmesh"
        sys.stdout.write(rule(account))
        return 0
    if "--path" in argv:
        sys.stdout.write(WRAPPER_PATH + "\n")
        return 0
    print("usage: nmesh_sudoers.py --wrapper | --rule <account> | --path",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
